#!/bin/bash
Fugaz
Tan verde fue el brote entre los dos
Tan meteorico fue el ascenso de la union
Tan vanidoso fue el brice de la conjucion
Tan psicologico fue el actuar
Tan tenue fue el epilogo de la conclusion
Tan viral fue la expancion de la despedida
Tan grande fue la colonizacuon patoligica de tu adios
Tan senescente tu mano sobre la mia
opera prima que no culmina
desasociego cuspide de una verdad implicita
Tan real y doloroso entender el adios desde la razon cuando
el corazon ya lo supero
